<?php

function oneclick_install() {
  db_query("UPDATE {system} SET weight = 50 WHERE type='module' and name='oneclick'");  
  variable_set('logintoboggan_redirect_on_register', 'user/verify');
  variable_set('logintoboggan_redirect_on_confirm', 'user/add/site');
  variable_set('hosting_feature_client', TRUE);
  variable_set('oneclick_default_profile', 'openweb');
}

function oneclick_uninstall() {
  return;
}
