<?php

/**
 * Implementation of hook_menu() 
 */
function oneclick_client_menu() {
  
  $items['waiting'] = array(
    'page callback' => 'oneclick_client_is_waiting',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function oneclick_client_init() {
  //variable_set('site_waiting', TRUE); 
  //exit();
  if (!user_is_logged_in()) {

    if (variable_get('site_waiting', TRUE)) {
      variable_set('site_waiting', FALSE);
      variable_set('root_site', 'openweb.in.th');

      drupal_http_request('http://'.variable_get('root_site', '').'/create_sitecon/'.variable_get('site_name', 'localhost').'?return=true');
      $_GET['return'] = 'true';
      oneclick_create_sitecon_client(variable_get('root_site', ''));

      $resp = drupal_http_request('http://'.variable_get('root_site', '').'/get_user_from_client/'.variable_get('site_name', 'localhost').'?format=json');

      $roles = user_roles();
      unset($roles[0]);
      $user = (array) json_decode($resp->data);
      $uid = db_result(db_query("SELECT uid FROM {users} WHERE name = '%s'", array($user['name'])));
      if (empty($uid)) {
        $pass = $user['pass'];
        $user['roles'] = $roles;
        $user['status'] = 1;
        $user = user_save('', $user);
        db_query("UPDATE {users} SET pass = '%s' WHERE uid = %d", array($pass, $user->uid));
      }
      drupal_goto('http://'.variable_get('root_site', '').'/sitecon/client/connect/'.variable_get('site_name', 'localhost').'/login', 'redirect=http://'.variable_get('site_name', 'localhost'));
    } 
  }  
  
}

function oneclick_client_is_waiting() {
  print $_GET['callback'].'('.json_encode(array('waiting' => variable_get('site_waiting', TRUE))).')';
}


